//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personel()
        {
            this.Tbl_UrunHareket = new HashSet<Tbl_UrunHareket>();
        }
    
        public int PersonelId { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string TC { get; set; }
        public string YabanciKimlikNo { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> IseBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
        public Nullable<int> Departman { get; set; }
        public Nullable<int> Gorev { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> Durum { get; set; }
        public string KimlikOn { get; set; }
        public string KimlikArka { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
    
        public virtual Tbl_Departman Tbl_Departman { get; set; }
        public virtual Tbl_Durum Tbl_Durum { get; set; }
        public virtual Tbl_Gorev Tbl_Gorev { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UrunHareket> Tbl_UrunHareket { get; set; }
    }
}
